### ISSUE TITLE
[Bug] cookie-parser should be called with response.cookies

### ISSUE THREAD

**Issue by jiachen247** [rocketacademy/bootcamp-docs#4]
cookie-parser should be called with `response.cookies` instead of `response.cookie`.

Here are all the occurrences I could find!
https://github.com/search?q=response.cookie%28+repo%3Arocketacademy%2Fbootcamp-docs&type=Code

**Comment by awongh** [comment]
I believe this is the correct syntax? Are you seeing errors @jiachen247 ?

`response` cookie is singular because one call only sets one cookie as a key-value pair in the response:

https://expressjs.com/en/5x/api.html#res.cookie

`request` gets the entire hash (object) of cookies because all cookie keys are set in this object:

https://expressjs.com/en/5x/api.html#req.cookies

**Comment by jiachen247** [comment]
Oh yes so sorry it's my bad I might have mixed up req and res - silly mistake! Thanks for reviewing @awongh !
